### PR TITLE
add imgvue.online

### PR DESCRIPTION
**Pull request by qupo1**

### CODE REVIEW

**Comment by zubrRB** [comment]
For some reason the script is not updated.

**Comment by Owyn** [comment]
> For some reason the script is not updated.

Check for updates doesn't happen every minute, see your tampermonkey extension settings for how frequently it happens

**Comment by zubrRB** [comment]
When manually checking for updates, neither AdGuard nor Tampermonkey sees updates.
Tampermonkey has now only been updated to the old version 2023.02.05.

HI

**Comment by Owyn** [comment]
You could also check your update URL 
image

**Comment by zubrRB** [comment]
I have the same link, but yours is also not updated to version `2023.02.11`.

**Comment by zubrRB** [comment]
Now updated.

**Comment by Owyn** [comment]
See, you just had to wait, no need to panic :-)

**Comment by zubrRB** [comment]
I used to always update immediately with a manual check.

**Pull request merged**
