### PR TITLE
Fix imguniversal.com

### PR DESCRIPTION
**Pull request by moham96**

### CODE REVIEW

**Comment by Owyn** [comment]
Does it also work on :
	case "imagebucks.biz":
	case "imgrock.net":
	case "myimg.club":
	case "imgview.net":
	case "imgwel.com":
	case "imgmonkey.com":
	case "imgdragon.com":
	case "imggold.org":
	case "imgtown.net":
?
because you are changing those too

**Comment by moham96** [comment]
Yeah I'm sorry, I didn't notice that, i only tasted it on imguniversal.com
because i had problem with it

**Comment by Owyn** [comment]
You can post the problematic link and I'll see what can be done there.

**Comment by moham96** [comment]
Yes i know, but it was a simple fix i did it myself and wanted to pass the
fix, unfortunately i didn't keep in mind the other host that where in the
same case.
Sorry for this misunderstanding and thank you for your work

**Pull request closed without merging**
