### PR TITLE
Remove ads pop-ups on click

### PR DESCRIPTION
**Pull request by MokhamedDakhraui**
Empty arrays contain ads urls to prevent opening ads pop-up instead of actual image page when click is triggered.

### CODE REVIEW

**Comment by Owyn** [comment]
There aren't any ads or pop-ups on click on imgadult.com for me even without any adblock plugin in both Firefox and Chrome, check that you don't have viruses or other extensions doing it

**Comment by MokhamedDakhraui** [comment]
Script that triggered ads popups is https://imgdrive.net/newimg.js.php?v=3.

I'm able to reproduce on `edge` and `chrome` after clearing cookies.
Example uri: https://imgdrive.net/img-557ddd3ac5de8.html

Code that opens popups:
```js
  $('a.overlay_ad_link').click(function(e) {
    if (window.ctipops.length && openPops(window.ctipops))
      return e.preventDefault();
    var ref="";
    if (window.ctiref)
      ref=window.ctiref;
    $.post(location.href, {cti: 1, ref: ref, rc: document.getElementById("TestAdBlock")!=undefined?1:0, rp: isPopupBlocked?0:1, bt: huEvts<8?1:0, bw: browser(), ic: isChrome()?1:0}, function(data) {
      setTimeout(function() {
        window.location.href = window.location.href;
      }, 10);
    }, "text");
```

**Comment by Owyn** [comment]
Even with cleared cookies chrome works fine

Are you perhaps doing something you shouldn't before only image is left, like clicking the mouse yourself to "continue to image" ?

**Comment by MokhamedDakhraui** [comment]
> Are you perhaps doing something you shouldn't before only image is left, like clicking the mouse yourself to "continue to image" ?
Conduct a clean experiment (edge):
image
Originally I notice that click worked not every time in `chrome`. After investigation I found code above that causing such behavior. It can be geo specific thing. Do you have something in `window.ctipops`?

P.S. But in chrome I'm unable to reproduce in via js. I'll make another attempt later

**Comment by MokhamedDakhraui** [comment]
Oh, I get it now. It appers only after adblock is enabled and is caused by code:
```js
    if (document.getElementById("TestAdBlock")==undefined) {
      window.cticodes=window.adbcticodes;
      window.ctipops=window.adbctipops;
    }
```
So to reproduce it you should block #TestAdBlock element before scripts were loaded.

**Comment by Owyn** [comment]
Microsoft Edge is not supported by the script. Use either Chrome or Firefox - it works fine there.

**Comment by MokhamedDakhraui** [comment]
Reproduced in chrome and firefox with enabled adblock

**Comment by MokhamedDakhraui** [comment]
And tags intensity is increasing 😄

**Comment by Owyn** [comment]
What kind of adblock? adblock called "ADBlock" (haven't heard about anyone still using it for years)? 
cuz with adblock (or without any adblock) called 'uBlock" it works fine on both

+ you can turn off your adblock for the specific website, can you not?

**Comment by MokhamedDakhraui** [comment]
image

AdBlock Plus
I'm not insisting on this change. I can apply it locally (better then turning off adblock on these sites or install a particular adblock that works for this script). Just thought it would be better to share the patch.
Not sure why you rejecting this change so strongly. It's literally emptying array with ad urls.

**Comment by Owyn** [comment]
firstly it'd break `imgadult.com` cuz images there have different url, 

secondly patch is intended as a fix for using an outdated badly-working (it should block that pop-up yet it doesn't) third party extension adblocker which has nothing to do with the userscript itself,

in a Microsoft default browser which is not supported

but thank you for the attempt to make the script better.

**Comment by MokhamedDakhraui** [comment]
> firstly it'd break imgadult.com cuz images there have different url,

`imgadult.com` is handling the exact same way as other three sites (word to word).
Additionally, event if variables `adbctipops`, `ctipops` will be missing that won't break script. If I'm missing something feel it'd be nice if you'll correct me.

Considering second reason. Plugins are not outdated and sufficiently popular.

But you have your right. Anyway, thanks for discussing issue.

**Pull request closed without merging**
